import { StackConfig } from '../cli/types.js';
import { AdapterFile, AdapterDependency } from '../adapters/index.js';
import { TEMPLATE_REGISTRY } from './registry.js';
import { getFrontendGlobalStyles, getFrontendAppStyles } from './shared/styles.js';
import { getStackmintLogoFile } from './shared/logo.js';
import { buildStackmintConfigLib } from './shared/config.js';
import { buildProviderComponents, buildUtilsFile } from './shared/providers.js';
import { buildTestingSetup, buildPlaywrightConfig } from './shared/testing.js';
import { buildDockerfile } from './shared/docker.js';
import { buildAuthFiles } from './shared/auth.js';

TEMPLATE_REGISTRY.set('astro-ssr', {

  id: 'astro-ssr',
  files: (config: StackConfig): AdapterFile[] => {
    const providerFiles = buildProviderComponents(config);
    const utilsFile = buildUtilsFile();
    const testingFiles = buildTestingSetup(config);
    const dockerfile = buildDockerfile(config);
    const authFiles = buildAuthFiles(config);

    const files: AdapterFile[] = [
    {
      path: 'stackmint.config.json',
      content: JSON.stringify(config, null, 2),
    },
    {
      path: 'src/server/public/health.ts',
      content: `export function getHealthPayload() {
  return {
    status: 'ok',
    framework: 'astro-ssr',
    timestamp: new Date().toISOString(),
  };
}
`,
    },
    {
      path: 'src/lib/stackmint-config.ts',
      content: buildStackmintConfigLib(config),
    },
    getStackmintLogoFile(),
    {
      path: 'src/pages/index.astro',
      content: `---
import '../styles/global.css';
import { getFrameworkDescription, getFrameworkLabel, getSignals, getStackMintConfig } from '../lib/stackmint-config';

const config = getStackMintConfig();
const signals = getSignals(config);
const frameworkLabel = getFrameworkLabel(config.framework);
const frameworkDescription = getFrameworkDescription(config);

let launches = 1;
---

<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>Astro SSR | Built with stackmint</title>
    <meta name="viewport" content="width=device-width" />
    <meta name="description" content="A creative Astro SSR starter generated by stackmint." />
  </head>
  <body>
    <div class="stackmint-shell">
      <header class="topbar">
        <a class="brand-mark" href="/">
          <span class="brand-glyph">S</span>
          <span class="brand-name">
            <strong>stackmint</strong>
            <span>TypeScript starter</span>
          </span>
        </a>
        <nav class="flex items-center gap-4">
          <a class="topbar-link" href="https://github.com/senapati484/stackmint" target="_blank" rel="noreferrer">
            GitHub
          </a>
        </nav>
      </header>

      <main class="hero">
        <section class="hero-copy">
          <span class="eyebrow">
            <span class="pulse" /> Built with stackmint
          </span>
          <h1>
            Shape your <span class="accent">{frameworkLabel}</span> launch surface.
          </h1>
          <p class="hero-lede">
            A production-ready Astro SSR template with optimized configuration,
            type-safe integrations, and a modern architecture.
          </p>

          <div class="actions">
            <button
              class="button button-primary"
              onclick={\`launches++; this.textContent = 'Launch pulse ' + launches\`}
            >
              Launch pulse {launches}
            </button>
            <a class="button button-secondary" href="/api/health">
              Check API health
            </a>
          </div>

          <div class="signal-grid">
            {signals.map((s) => (
              <article class="signal-card">
                <span>{s.label}</span>
                <strong>{s.value}</strong>
                <p>{s.detail}</p>
              </article>
            ))}
          </div>
        </section>

        <section class="hero-visual">
          <div class="logo-stage">
            <img class="logo-image" src="/logo.png" alt="stackmint" />
          </div>
          <aside class="framework-card">
            <span>Stack overview</span>
            <strong>{frameworkLabel}</strong>
            <p>{frameworkDescription}</p>
          </aside>
        </section>
      </main>

      <footer class="footer-note">
        Built with stackmint · The Ultimate TypeScript Starter
      </footer>
    </div>
  </body>
</html>
`,
    },
    getStackmintLogoFile(),
    {
      path: 'src/styles/global.css',
      content: `${getFrontendGlobalStyles()}
${getFrontendAppStyles()}`,
    },
    {
      path: 'src/pages/api/health.ts',
      content: `import { getHealthPayload } from '../../server/public/health';

export const prerender = false;

export async function GET() {
    return new Response(JSON.stringify({
        ...getHealthPayload()
    }), {
        headers: { 'Content-Type': 'application/json' }
    });
}
`,
    },
    {
      path: 'astro.config.mjs',
      content: `import { defineConfig } from 'astro/config';
import node from '@astrojs/node';
import tailwindcss from '@tailwindcss/vite';

export default defineConfig({
    output: 'server',
    adapter: node({
        mode: 'standalone'
    }),
    server: {
        port: 3000
    },
    vite: {
        plugins: [
            tailwindcss(),
            {
                name: 'stackmint-port-logger',
                configureServer(server) {
                    server.httpServer?.once('listening', () => {
                        const address = server.httpServer?.address();
                        const port = typeof address === 'object' ? address?.port : null;
                        if (port) {
                            console.log(\`\\n✨ Server running at http://localhost:\${port}\\n\`);
                        }
                    });
                }
            }
        ]
    },
});
`,
    },
    {
      path: 'tsconfig.json',
      content: JSON.stringify({
        extends: 'astro/tsconfigs/base'
      }, null, 2),
    },
    ...providerFiles,
    utilsFile,
    ...testingFiles,
    ...(dockerfile ? [dockerfile] : []),
    ...(config.testing?.includes('playwright') ? [buildPlaywrightConfig()] : []),
    ];

    return files;
  },

  scripts: (config: StackConfig): Record<string, string> => {
    const scripts: Record<string, string> = {
      dev: 'astro dev',
      build: 'astro build',
      start: 'node ./dist/server/entry.mjs',
    };

    if (config.testing?.includes('vitest')) {
      scripts.test = 'vitest run';
      scripts['test:watch'] = 'vitest';
    }

    if (config.testing?.includes('playwright')) {
      scripts['test:e2e'] = 'playwright test';
    }

    return scripts;
  },

  dependencies: (config: StackConfig): AdapterDependency[] => {
    const deps: AdapterDependency[] = [];

    if (config.styling === 'tailwind' || config.uiLibrary === 'shadcn') {
      deps.push({ name: 'next-themes', version: '^0.4.3' });
    }

    if (config.uiLibrary === 'shadcn') {
      deps.push({ name: 'sonner', version: '^1.7.0' });
    }

    if (config.testing?.includes('vitest')) {
      deps.push(
        { name: '@testing-library/jest-dom', version: '^6.6.0', dev: true },
        { name: 'vitest', version: '^2.0.0', dev: true },
      );
    }

    return deps;
  },
});
