import { StackConfig } from '../cli/types.js';
import { AdapterFile, AdapterDependency } from '../adapters/index.js';
import { TEMPLATE_REGISTRY } from './registry.js';
import { getFrontendGlobalStyles, getFrontendAppStyles } from './shared/styles.js';
import { getStaticFrontendMarkup, getStaticFrontendHTML } from './shared/markup.js';
import { getStackmintLogoFile } from './shared/logo.js';

TEMPLATE_REGISTRY.set('astro-ssr', {

  id: 'astro-ssr',
  files: (config: StackConfig): AdapterFile[] => [
    {
      path: 'stackmint.config.json',
      content: JSON.stringify(config, null, 2),
    },
    {
      path: 'src/server/public/health.ts',
      content: `export function getHealthPayload() {
  return {
    status: 'ok',
    framework: 'astro-ssr',
    timestamp: new Date().toISOString(),
  };
}
`,
    },
    getStackmintLogoFile(),
    {
      path: 'src/pages/index.astro',
      content: `---
import '../styles/global.css';
---

<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>Astro SSR | Built with stackmint</title>
    <meta name="viewport" content="width=device-width" />
    <meta name="description" content="A creative Astro SSR starter generated by stackmint." />
  </head>
  <body>
    <Fragment set:html={\`${getStaticFrontendMarkup({
        framework: 'Astro SSR',
        runtime: 'Astro SSR',
        styling: 'Tailwind v4',
        build: 'Server',
        detail: 'Astro server rendering, API routes, and Tailwind v4 share the stackmint frontend shell.',
        editPath: 'src/pages/index.astro',
        actionHref: '/api/health',
        actionLabel: 'Check API health',
      })}\`} />
  </body>
</html>
`,
    },
    getStackmintLogoFile(),
    {
      path: 'src/styles/global.css',
      content: `${getFrontendGlobalStyles()}
${getFrontendAppStyles()}`,
    },
    {
      path: 'src/pages/api/health.ts',
      content: `import { getHealthPayload } from '../../server/public/health';

export const prerender = false;

export async function GET() {
    return new Response(JSON.stringify({
        ...getHealthPayload()
    }), {
        headers: { 'Content-Type': 'application/json' }
    });
}
`,
    },
    {
      path: 'astro.config.mjs',
      content: `import { defineConfig } from 'astro/config';
import node from '@astrojs/node';
import tailwindcss from '@tailwindcss/vite';

export default defineConfig({
    output: 'server',
    adapter: node({
        mode: 'standalone'
    }),
    server: {
        port: 3000
    },
    vite: {
        plugins: [
            tailwindcss(),
            {
                name: 'stackmint-port-logger',
                configureServer(server) {
                    server.httpServer?.once('listening', () => {
                        const address = server.httpServer?.address();
                        const port = typeof address === 'object' ? address?.port : null;
                        if (port) {
                            console.log(\`\\n✨ Server running at http://localhost:\${port}\\n\`);
                        }
                    });
                }
            }
        ]
    },
});
`,
    },
    {
      path: 'tsconfig.json',
      content: JSON.stringify({
        extends: 'astro/tsconfigs/base'
      }, null, 2),
    },
  ],
  scripts: {
    dev: 'astro dev',
    build: 'astro build',
    start: 'node ./dist/server/entry.mjs',
  },
});
