import { StackConfig } from '../cli/types.js';
import { AdapterFile, AdapterDependency } from '../adapters/index.js';
import { TEMPLATE_REGISTRY } from './registry.js';
import { getFrontendGlobalStyles, getFrontendAppStyles } from './shared/styles.js';
import { getStaticFrontendMarkup, getStaticFrontendHTML } from './shared/markup.js';
import { getStackmintLogoFile } from './shared/logo.js';

TEMPLATE_REGISTRY.set('astro-ssg', {

  id: 'astro-ssg',
  files: (): AdapterFile[] => [
    getStackmintLogoFile(),
    {
      path: 'src/pages/index.astro',
      content: `---
import '../styles/global.css';
---

<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>Astro | Built with stackmint</title>
    <meta name="viewport" content="width=device-width" />
    <meta name="description" content="A creative Astro starter generated by stackmint." />
  </head>
  <body>
    <Fragment set:html={\`${getStaticFrontendMarkup({
        framework: 'Astro',
        runtime: 'Astro SSG',
        styling: 'Tailwind v4',
        build: 'Static',
        detail: 'Astro content pages and Tailwind v4 share the stackmint frontend shell.',
        editPath: 'src/pages/index.astro',
        actionHref: 'https://stackmint-docs.vercel.app',
        actionLabel: 'Open docs',
      })}\`} />
  </body>
</html>
`,
    },
    getStackmintLogoFile(),
    {
      path: 'src/styles/global.css',
      content: `${getFrontendGlobalStyles()}
${getFrontendAppStyles()}`,
    },
    {
      path: 'src/layouts/Layout.astro',
      content: `---
const { title } = Astro.props;
---

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>{title}</title>
    <meta name="viewport" content="width=device-width" />
  </head>
  <body>
    <slot />
  </body>
</html>
`,
    },
    {
      path: 'astro.config.mjs',
      content: `import { defineConfig } from 'astro/config';
import tailwindcss from '@tailwindcss/vite';

export default defineConfig({
    output: 'static',
    server: {
        port: 3000
    },
    vite: {
        plugins: [
            tailwindcss(),
            {
                name: 'stackmint-port-logger',
                configureServer(server) {
                    server.httpServer?.once('listening', () => {
                        const address = server.httpServer?.address();
                        const port = typeof address === 'object' ? address?.port : null;
                        if (port) {
                            console.log(\`\\n✨ Server running at http://localhost:\${port}\\n\`);
                        }
                    });
                }
            }
        ]
    },
});
`,
    },
    {
      path: 'tsconfig.json',
      content: JSON.stringify({
        extends: 'astro/tsconfigs/base'
      }, null, 2),
    },
  ],
  scripts: {
    dev: 'astro dev',
    build: 'astro build',
    preview: 'astro preview',
  },
});