import { StackConfig } from '../cli/types.js';
import { AdapterFile, AdapterDependency } from '../adapters/index.js';
import { TEMPLATE_REGISTRY } from './registry.js';
import { getFrontendGlobalStyles, getFrontendAppStyles } from './shared/styles.js';
import { getStaticFrontendMarkup, getStaticFrontendHTML } from './shared/markup.js';
import { getStackmintLogoFile } from './shared/logo.js';

TEMPLATE_REGISTRY.set('docusaurus', {

  id: 'docusaurus',
  files: (): AdapterFile[] => [
    {
      path: 'docs/intro.md',
      content: `---
slug: /
---

# Welcome to Stackmint Docs

This is your Docusaurus documentation site, powered by stackmint.

## Getting Started

Edit the docs in the \`docs/\` folder to customize your documentation.

### Next Steps

- Edit \`docs/intro.md\` to customize this homepage
- Add more pages in the \`docs/\` directory
- Update \`docusaurus.config.ts\` with your site information
`,
    },
    {
      path: 'docusaurus.config.ts',
      content: `import {Config} from '@docusaurus/types';
import {Options} from '@docusaurus/preset-classic';

const config: Config = {
  title: 'stackmint docs',
  tagline: 'Built with stackmint',
  favicon: 'img/favicon.ico',
  url: 'https://your-docusaurus-test-site.com',
  baseUrl: '/',
  organizationName: 'stackmint',
  projectName: 'docusaurus-site',
  onBrokenLinks: 'throw',
  onBrokenMarkdownLinks: 'warn',
  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },
  presets: [
    [
      'classic',
      {
        docs: {
          sidebarPath: './sidebars.ts',
          editUrl: 'https://github.com/stackmint/docusaurus-site/tree/main/',
        },
        blog: {
          showReadingTime: true,
          editUrl: 'https://github.com/stackmint/docusaurus-site/tree/main/',
        },
        theme: {
          customCss: './src/css/custom.css',
        },
      } satisfies Options,
    ],
  ],
  themeConfig: {
    navbar: {
      title: 'stackmint',
      items: [
        {to: '/docs/intro', label: 'Docs', position: 'left'},
        {href: 'https://github.com/stackmint', label: 'GitHub', position: 'right'},
      ],
    },
    footer: {
      style: 'dark',
      copyright: \`Built with stackmint. © \${new Date().getFullYear()}.\`,
    },
  },
};

export default config;
`,
    },
    {
      path: 'sidebars.ts',
      content: `import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
`,
    },
    {
      path: 'src/css/custom.css',
      content: `/**
 * Any CSS included here will be global. The classic template
 * bundles Infima by default. Infima is a simple framework used to
 * create the basic look and feel of the Docusaurus site.
 */

/* You can override the default Infima variables here. */
:root {
  --ifm-color-primary: #2e8555;
  --ifm-color-primary-dark: #29784c;
  --ifm-color-primary-darker: #277148;
  --ifm-color-primary-darkest: #205d3b;
  --ifm-color-primary-light: #33925d;
  --ifm-color-primary-lighter: #359962;
  --ifm-color-primary-lightest: #3cad6e;
}
`,
    },
  ],
  scripts: { dev: 'docusaurus start', build: 'docusaurus build' },
});