import { StackConfig } from '../cli/types.js';
import { AdapterFile, AdapterDependency } from '../adapters/index.js';
import { TEMPLATE_REGISTRY } from './registry.js';
import { getFrontendGlobalStyles, getFrontendAppStyles } from './shared/styles.js';
import { getStackmintLogoFile } from './shared/logo.js';

// ─── layout.tsx ─────────────────────────────────────────────────────────────
// Dynamically wraps {children} with the right provider tree based on config.

function buildLayoutContent(config: StackConfig): string {
  const appName = config.projectName || 'my-app';

  const extraImports: string[] = [];
  const providerOpens: string[] = [];
  const providerCloses: string[] = [];

  // Theme Provider (Standard for shadcn/Tailwind)
  if (config.styling === 'tailwind' || config.uiLibrary === 'shadcn') {
    extraImports.push(`import { ThemeProvider } from '@/components/providers/theme-provider';`);
    providerOpens.push(`        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem disableTransitionOnChange>`);
    providerCloses.unshift(`        </ThemeProvider>`);
  }

  // Auth Providers
  if (config.auth === 'clerk') {
    extraImports.push(`import { ClerkProvider } from '@clerk/nextjs';`);
    providerOpens.push(`          <ClerkProvider>`);
    providerCloses.unshift(`          </ClerkProvider>`);
  } else if (config.auth === 'next-auth') {
    extraImports.push(`import { SessionProvider } from 'next-auth/react';`);
    providerOpens.push(`          <SessionProvider>`);
    providerCloses.unshift(`          </SessionProvider>`);
  }

  // BaaS Providers
  if (config.baas === 'convex') {
    extraImports.push(`import { ConvexClientProvider } from '@/lib/convex';`);
    providerOpens.push(`            <ConvexClientProvider>`);
    providerCloses.unshift(`            </ConvexClientProvider>`);
  }

  // API / Data Fetching Providers
  if (config.apiLayer === 'trpc') {
    extraImports.push(`import { TRPCProvider } from '@/components/providers/trpc-provider';`);
    providerOpens.push(`              <TRPCProvider>`);
    providerCloses.unshift(`              </TRPCProvider>`);
  } else if (config.dataFetching === 'tanstack-query') {
    extraImports.push(`import { QueryProvider } from '@/components/providers/query-provider';`);
    providerOpens.push(`              <QueryProvider>`);
    providerCloses.unshift(`              </QueryProvider>`);
  }

  // Add Sonner Toaster if using shadcn or explicitly requested
  let toaster = '';
  if (config.uiLibrary === 'shadcn') {
    extraImports.push(`import { Toaster } from '@/components/ui/sonner';`);
    toaster = `\n        <Toaster position="top-right" />`;
  }

  const childrenBlock =
    providerOpens.length > 0
      ? [
          ...providerOpens,
          `                {children}`,
          ...providerCloses,
        ].join('\n')
      : `          {children}`;

  return `import type { Metadata, Viewport } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import React, { type ReactNode } from 'react';
${extraImports.join('\n')}

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: '${appName}',
  description: 'Generated by stackmint — the ultimate TypeScript starter.',
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  themeColor: '#05070c',
};

export default function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(inter.className, 'min-h-screen bg-background antialiased')}>
${childrenBlock}${toaster}
      </body>
    </html>
  );
}
`;
}

// ─── middleware.ts ───────────────────────────────────────────────────────────

function buildMiddlewareContent(config: StackConfig): string | null {
  // Clerk handles its own middleware
  if (config.auth === 'clerk') return null;

  // Modern middleware matcher that correctly excludes all static files
  const staticExclusion = '(?!api|_next/static|_next/image|favicon.ico|sitemap.xml|robots.txt|.*\\\\..*)';

  if (config.auth === 'next-auth') {
    return `import { auth } from '@/auth';

export default auth((req) => {
  // Add custom logic here if needed
});

export const config = {
  matcher: ['/((?!api|_next/static|_next/image|favicon.ico|.*\\\\..*).*)'],
};
`;
  }

  if (config.auth === 'better-auth') {
    return `import { NextRequest, NextResponse } from 'next/server';
import { getSessionCookie } from 'better-auth/cookies';

const PUBLIC_PATHS = ['/', '/api/health', '/sign-in', '/sign-up'];

export async function middleware(request: NextRequest) {
  const { pathname } = request.nextUrl;
  const sessionCookie = getSessionCookie(request);

  const isPublic =
    PUBLIC_PATHS.some((p) => pathname === p) ||
    pathname.startsWith('/api/auth') ||
    pathname.startsWith('/_next');

  if (!sessionCookie && !isPublic) {
    return NextResponse.redirect(new URL('/sign-in', request.url));
  }

  return NextResponse.next();
}

export const config = {
  matcher: ['/((?!_next/static|_next/image|favicon.ico|.*\\\\..*).*)'],
};
`;
  }

  if (config.baas === 'supabase') {
    return `import { type NextRequest } from 'next/server';
import { updateSession } from '@/lib/supabase/middleware';

export async function middleware(request: NextRequest) {
  return await updateSession(request);
}

export const config = {
  matcher: [
    '/((?!_next/static|_next/image|favicon.ico|.*\\\\.(?:svg|png|jpg|jpeg|gif|webp)$).*)',
  ],
};
`;
  }

  return null;
}

// ─── next.config.ts ─────────────────────────────────────────────────────────

function buildNextConfig(config: StackConfig, standalone = false): string {
  const lines: string[] = [`import type { NextConfig } from 'next';`, ``];

  lines.push(`const nextConfig: NextConfig = {`);
  lines.push(`  outputFileTracingRoot: process.cwd(),`);

  if (standalone) {
    lines.push(`  output: 'standalone', // Required for Docker builds`);
  }

  if (config.deployTarget === 'cloudflare-workers') {
    lines.push(`  // Cloudflare Next-on-Pages configuration`);
  }

  lines.push(`  eslint: { ignoreDuringBuilds: true },`);
  lines.push(`  typescript: { ignoreBuildErrors: true },`);
  lines.push(`};`);
  lines.push(``, `export default nextConfig;`);

  return lines.join('\n');
}

// ─── stackmint-config.ts ─────────────────────────────────────────────────────

function buildStackmintConfigLib(config: StackConfig): string {
  const frozen = {
    projectName: config.projectName || 'my-app',
    framework: config.framework || 'nextjs',
    category: config.category || 'fullstack',
    deployTarget: config.deployTarget || 'none',
    database: config.database || 'none',
    orm: config.orm || 'none',
    baas: config.baas || 'none',
    auth: config.auth || 'none',
    apiLayer: config.apiLayer || 'none',
    validation: config.validation || 'none',
    styling: config.styling || 'none',
    uiLibrary: config.uiLibrary || 'none',
    forms: config.forms || 'none',
    stateManagement: config.stateManagement || 'none',
    dataFetching: config.dataFetching || 'none',
    ai: config.ai || 'none',
    jobs: config.jobs || 'none',
    cache: config.cache || 'none',
    email: config.email || 'none',
    payments: config.payments || 'none',
    testing: config.testing || 'none',
    docker: !!config.docker,
    githubActions: !!config.githubActions,
    packageManager: config.packageManager || 'npm',
    runtime: config.runtime || 'node',
    monorepo: !!config.monorepo,
    aiConfig: config.aiConfig || [],
  };

  return `// Auto-generated by stackmint — do not edit manually.

export interface StackMintConfig {
  projectName: string; framework: string; category: string; deployTarget: string;
  database: string; orm: string; baas: string; auth: string; apiLayer: string;
  validation: string; styling: string; uiLibrary: string; forms: string;
  stateManagement: string; dataFetching: string; ai: string; jobs: string;
  cache: string; email: string; payments: string; testing: string;
  docker: boolean; githubActions: boolean; packageManager: string; runtime: string;
  monorepo: boolean; aiConfig: string[];
}

export function getStackMintConfig(): StackMintConfig {
  return ${JSON.stringify(frozen, null, 2)};
}

const FRAMEWORK_LABELS: Record<string, string> = {
  nextjs: 'Next.js 15', sveltekit: 'SvelteKit', nuxt: 'Nuxt 3',
  'react-router-v7': 'React Router v7', 'analog': 'Analog',
  'tanstack-start': 'TanStack Start', 'astro-ssr': 'Astro SSR',
};

export function getFrameworkLabel(id: string): string {
  return FRAMEWORK_LABELS[id] ?? id;
}

export interface Signal { label: string; value: string; detail: string; }

export function getSignals(config: StackMintConfig): Signal[] {
  const s: Signal[] = [];
  s.push({ label: 'Framework', value: getFrameworkLabel(config.framework), detail: 'App Router · React 19' });

  if (config.database !== 'none') {
    s.push({ label: 'Database', value: config.database, detail: 'Primary persistence' });
  } else if (config.baas !== 'none') {
    s.push({ label: 'Backend', value: config.baas, detail: 'Backend-as-a-Service' });
  }

  if (config.orm !== 'none') s.push({ label: 'ORM', value: config.orm, detail: 'Database access' });
  if (config.auth !== 'none') s.push({ label: 'Auth', value: config.auth, detail: 'Identity & Security' });
  if (config.apiLayer !== 'none') s.push({ label: 'API', value: config.apiLayer, detail: 'Data communication' });
  if (config.styling !== 'none') s.push({ label: 'Styling', value: config.styling, detail: 'Visual layer' });
  if (config.uiLibrary !== 'none') s.push({ label: 'UI', value: config.uiLibrary, detail: 'Component library' });
  if (config.ai !== 'none') s.push({ label: 'AI', value: config.ai, detail: 'Intelligence' });
  if (config.deployTarget !== 'none') s.push({ label: 'Deploy', value: config.deployTarget, detail: 'Cloud target' });

  return s;
}

export function getFrameworkDescription(config: StackMintConfig): string {
  const parts: string[] = [];
  if (config.database !== 'none') parts.push('database');
  if (config.auth !== 'none') parts.push('auth');
  if (config.apiLayer !== 'none') parts.push('API');
  return parts.length > 0
    ? \`Next.js 15 with \${parts.join(', ')}.\`
    : 'Next.js 15 — Ready for production.';
}
`;
}

// ─── src/app/page.tsx ────────────────────────────────────────────────────────

const PAGE_CONTENT = `'use client';

import { useState } from 'react';
import {
  getStackMintConfig,
  getSignals,
  getFrameworkLabel,
  getFrameworkDescription,
} from '@/lib/stackmint-config';

export default function HomePage() {
  const [launches, setLaunches] = useState(1);
  const config = getStackMintConfig();
  const signals = getSignals(config);
  const frameworkLabel = getFrameworkLabel(config.framework);
  const frameworkDescription = getFrameworkDescription(config);

  return (
    <div className="stackmint-shell">
      <header className="topbar">
        <a className="brand-mark" href="/">
          <span className="brand-glyph">S</span>
          <span className="brand-name">
            <strong>stackmint</strong>
            <span>TypeScript starter</span>
          </span>
        </a>
        <nav className="flex items-center gap-4">
          <a className="topbar-link" href="https://github.com/senapati484/stackmint" target="_blank" rel="noreferrer">
            GitHub
          </a>
        </nav>
      </header>

      <main className="hero">
        <section className="hero-copy">
          <span className="eyebrow">
            <span className="pulse" /> Built with stackmint
          </span>
          <h1>
            Shape your <span className="accent">{frameworkLabel}</span> launch surface.
          </h1>
          <p className="hero-lede">
            A production-ready Next.js 15 template with optimized configuration, 
            type-safe integrations, and a modern architecture.
          </p>

          <div className="actions">
            <button
              className="button button-primary"
              onClick={() => setLaunches((v) => v + 1)}
            >
              Launch pulse {launches}
            </button>
            <a className="button button-secondary" href="/api/health">
              Check API health
            </a>
          </div>

          <div className="signal-grid">
            {signals.map((s) => (
              <article className="signal-card" key={s.label}>
                <span>{s.label}</span>
                <strong>{s.value}</strong>
                <p>{s.detail}</p>
              </article>
            ))}
          </div>
        </section>

        <section className="hero-visual">
          <div className="logo-stage">
            <img className="logo-image" src="/logo.png" alt="stackmint" />
          </div>
          <aside className="framework-card">
            <span>Stack overview</span>
            <strong>{frameworkLabel}</strong>
            <p>{frameworkDescription}</p>
          </aside>
        </section>
      </main>

      <footer className="footer-note">
        Built with stackmint · The Ultimate TypeScript Starter
      </footer>
    </div>
  );
}
`;

// ─── globals.css ─────────────────────────────────────────────────────────────

function buildGlobalsCss(): string {
  return `${getFrontendGlobalStyles()}
${getFrontendAppStyles()}
/* Next.js 15 App Router Overrides */
@layer base {
  :root {
    --background: 0 0% 2%;
    --foreground: 0 0% 98%;
    --primary: 161 86% 58%;
    --primary-foreground: 161 86% 5%;
  }
}

.signal-grid {
  grid-template-columns: repeat(auto-fill, minmax(140px, 1fr));
}
`;
}

// ─────────────────────────────────────────────────────────────────────────────
// TEMPLATE REGISTRATION
// ─────────────────────────────────────────────────────────────────────────────

TEMPLATE_REGISTRY.set('nextjs', {
  id: 'nextjs',

  files: (config: StackConfig): AdapterFile[] => {
    const appName = config.projectName || 'my-app';
    const useDocker = !!config.docker;

    const files: AdapterFile[] = [
      {
        path: 'stackmint.config.json',
        content: JSON.stringify(config, null, 2),
      },
      { path: 'src/app/layout.tsx', content: buildLayoutContent(config) },
      { path: 'src/app/page.tsx', content: PAGE_CONTENT },
      { path: 'src/app/globals.css', content: buildGlobalsCss() },
      {
        path: 'src/app/api/(public)/health/route.ts',
        content: `import { NextResponse } from 'next/server';

export async function GET() {
  return NextResponse.json({
    status: 'ok',
    framework: 'nextjs',
    app: '${appName}',
    timestamp: new Date().toISOString(),
  });
}
`,
      },
      { path: 'src/lib/stackmint-config.ts', content: buildStackmintConfigLib(config) },
      {
        path: 'src/lib/utils.ts',
        content: `import { clsx, type ClassValue } from 'clsx';
import { twMerge } from 'tailwind-merge';

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}
`,
      },
      {
        path: 'src/components/providers/theme-provider.tsx',
        content: `'use client';

import * as React from 'react';
import { ThemeProvider as NextThemesProvider } from 'next-themes';

export function ThemeProvider({ children, ...props }: React.ComponentProps<typeof NextThemesProvider>) {
  return <NextThemesProvider {...props}>{children}</NextThemesProvider>;
}
`,
      },
      getStackmintLogoFile(),
      { path: 'public/.gitkeep', content: '' },
      { path: 'next.config.ts', content: buildNextConfig(config, useDocker) },
      {
        path: 'tsconfig.json',
        content: JSON.stringify({
          compilerOptions: {
            target: 'ES2017',
            lib: ['dom', 'dom.iterable', 'esnext'],
            allowJs: true,
            skipLibCheck: true,
            strict: true,
            noEmit: true,
            esModuleInterop: true,
            module: 'esnext',
            moduleResolution: 'bundler',
            resolveJsonModule: true,
            isolatedModules: true,
            jsx: 'preserve',
            incremental: true,
            plugins: [{ name: 'next' }],
            paths: { '@/*': ['./src/*'] },
          },
          include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
          exclude: ['node_modules'],
        }, null, 2),
      },
      {
        path: 'postcss.config.mjs',
        content: `export default {
  plugins: {
    '@tailwindcss/postcss': {},
  },
};
`,
      },
    ];

    const middlewareContent = buildMiddlewareContent(config);
    if (middlewareContent) {
      files.push({ path: 'src/middleware.ts', content: middlewareContent });
    }

    if (config.auth === 'next-auth') {
      files.push(
        {
          path: 'src/auth.ts',
          content: `import NextAuth from 'next-auth';
import GitHub from 'next-auth/providers/github';

export const { handlers, signIn, signOut, auth } = NextAuth({
  providers: [GitHub],
});
`,
        },
        {
          path: 'src/app/api/(auth)/auth/[...nextauth]/route.ts',
          content: `import { handlers } from '@/auth';
export const { GET, POST } = handlers;
`,
        },
      );
    }

    if (config.testing === 'vitest' || config.testing === 'vitest+playwright') {
      files.push(
        {
          path: 'vitest.config.ts',
          overwrite: true,
          content: `import { defineConfig } from 'vitest/config';
import react from '@vitejs/plugin-react';
import tsconfigPaths from 'vite-tsconfig-paths';

export default defineConfig({
  plugins: [react(), tsconfigPaths()],
  test: {
    globals: true,
    environment: 'jsdom',
    setupFiles: ['./tests/setup.ts'],
    include: ['**/*.test.{ts,tsx}'],
  },
});
`,
        },
        {
          path: 'tests/setup.ts',
          overwrite: true,
          content: `import '@testing-library/jest-dom';
import { cleanup } from '@testing-library/react';
import { afterEach } from 'vitest';

afterEach(() => cleanup());
`,
        },
      );
    }

    if (useDocker) {
      files.push({
        path: 'Dockerfile',
        overwrite: true,
        content: `# syntax=docker/dockerfile:1
FROM node:20-alpine AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm ci

FROM node:20-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
ENV NEXT_TELEMETRY_DISABLED=1
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
RUN addgroup --system --gid 1001 nodejs && adduser --system --uid 1001 nextjs
COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
USER nextjs
EXPOSE 3000
ENV PORT=3000 HOSTNAME="0.0.0.0"
CMD ["node", "server.js"]
`,
      });
    }

    return files;
  },

  scripts: (config: StackConfig): Record<string, string> => {
    const scripts: Record<string, string> = {
      dev: 'next dev --turbopack',
      build: 'next build',
      start: 'next start',
      lint: 'next lint',
      'type-check': 'tsc --noEmit',
    };

    if (config.testing?.includes('vitest')) {
      scripts.test = 'vitest run';
      scripts['test:watch'] = 'vitest';
    }

    if (config.testing?.includes('playwright')) {
      scripts['test:e2e'] = 'playwright test';
    }

    return scripts;
  },

  dependencies: (config: StackConfig): AdapterDependency[] => {
    const deps: AdapterDependency[] = [
      { name: 'clsx', version: '^2.1.1' },
      { name: 'tailwind-merge', version: '^2.5.4' },
      { name: 'lucide-react', version: '^0.460.0' },
    ];

    if (config.styling === 'tailwind' || config.uiLibrary === 'shadcn') {
      deps.push({ name: 'next-themes', version: '^0.4.3' });
    }

    if (config.uiLibrary === 'shadcn') {
      deps.push({ name: 'sonner', version: '^1.7.0' });
    }

    if (config.auth === 'next-auth') {
      deps.push({ name: 'next-auth', version: '5.0.0-beta.25' });
    }

    if (config.testing?.includes('vitest')) {
      deps.push(
        { name: '@testing-library/react', version: '^16.0.0', dev: true },
        { name: '@testing-library/jest-dom', version: '^6.6.0', dev: true },
        { name: '@vitejs/plugin-react', version: '^4.3.0', dev: true },
        { name: 'vite-tsconfig-paths', version: '^5.1.0', dev: true },
        { name: 'jsdom', version: '^25.0.0', dev: true },
      );
    }

    return deps;
  },
});
