import { StackConfig } from '../cli/types.js';
import { AdapterFile, AdapterDependency } from '../adapters/index.js';
import { TEMPLATE_REGISTRY } from './registry.js';
import { getFrontendGlobalStyles, getFrontendAppStyles } from './shared/styles.js';
import { getStaticFrontendMarkup, getStaticFrontendHTML } from './shared/markup.js';
import { getStackmintLogoFile } from './shared/logo.js';

TEMPLATE_REGISTRY.set('nextjs', {

  id: 'nextjs',
  files: (config: StackConfig): AdapterFile[] => {
    const files: AdapterFile[] = [
      {
        path: 'stackmint.config.json',
        content: JSON.stringify({
          projectName: config.projectName,
          framework: config.framework,
          category: config.category,
          deployTarget: config.deployTarget,
          database: config.database,
          auth: config.auth,
          apiLayer: config.apiLayer,
          validation: config.validation,
          styling: config.styling,
          uiLibrary: config.uiLibrary,
          forms: config.forms,
          stateManagement: config.stateManagement,
          dataFetching: config.dataFetching,
          ai: config.ai,
          jobs: config.jobs,
          cache: config.cache,
          email: config.email,
          payments: config.payments,
          testing: config.testing,
          docker: config.docker,
          githubActions: config.githubActions,
          husky: config.husky,
          changesets: config.changesets,
          turborepo: config.turborepo,
          baas: config.baas,
          orm: config.orm,
          packageManager: config.packageManager,
          runtime: config.runtime,
        }, null, 2),
      },
      {
        path: 'src/app/layout.tsx',
        content: `import type { Metadata, Viewport } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: '${config.projectName || 'my-app'} | Built with stackmint',
  description: 'A creative Next.js starter generated by stackmint.',
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
`,
      },
      {
        path: 'src/app/page.tsx',
        content: `'use client';

import { useState } from 'react';
import { getStackMintConfig, getFrameworkLabel, getSignals, getFrameworkDescription } from '../lib/stackmint-config';

export default function HomePage() {
  const [launches, setLaunches] = useState(1);
  const config = getStackMintConfig();
  const signals = getSignals(config);
  const frameworkLabel = getFrameworkLabel(config.framework);
  const frameworkDescription = getFrameworkDescription(config);

  return (
    <div className="stackmint-shell">
      <header className="topbar">
        <a className="brand-mark" href="https://stackmint-docs.vercel.app" target="_blank" rel="noreferrer">
          <span className="brand-glyph">S</span>
          <span className="brand-name">
            <strong>stackmint</strong>
            <span>TypeScript starter</span>
          </span>
        </a>
        <a className="topbar-link" href="https://github.com/senapati484/stackmint" target="_blank" rel="noreferrer">
          GitHub
        </a>
      </header>

      <main className="hero">
        <section className="hero-copy" aria-labelledby="hero-title">
          <span className="eyebrow"><span className="pulse" /> Prebuilt frontend template</span>
          <h1 id="hero-title">
            Shape your <span className="accent">{frameworkLabel}</span> launch surface.
          </h1>
          <p className="hero-lede">
            A polished stackmint canvas with real brand artwork, responsive panels,
            and a consistent layout ready to mirror across every frontend framework.
          </p>

          <div className="actions">
            <button className="button button-primary" type="button" onClick={() => setLaunches((value) => value + 1)}>
              Launch pulse {launches}
            </button>
            <a className="button button-secondary" href="/api/health">
              Check API health
            </a>
          </div>

          <div className="signal-grid" aria-label="Template highlights">
            {signals.map((signal) => (
              <article className="signal-card" key={signal.label}>
                <span>{signal.label}</span>
                <strong>{signal.value}</strong>
                <p>{signal.detail}</p>
              </article>
            ))}
          </div>
        </section>

        <section className="hero-visual" aria-label="stackmint preview">
          <div className="logo-stage">
            <img className="logo-image" src="/logo.png" alt="stackmint" />
          </div>
          <aside className="framework-card">
            <span>Framework section</span>
            <strong>{frameworkLabel}</strong>
            <p>{frameworkDescription}</p>
          </aside>

          <div className="status-row">
            <div className="mini-panel">
              <span>Edit surface</span>
              <strong><code>src/app/page.tsx</code></strong>
            </div>
            <div className="mini-panel">
              <span>Health route</span>
              <strong><code>/api/health</code></strong>
            </div>
          </div>
        </section>
      </main>

      <footer className="footer-note">
        Built with stackmint. Keep this layout and swap framework section as new templates come online.
      </footer>
    </div>
  );
}
`,
      },
      {
        path: 'src/app/globals.css',
        content: `${getFrontendGlobalStyles()}
${getFrontendAppStyles()}`,
      },
      {
        path: 'src/app/api/health/route.ts',
        content: `import { NextResponse } from 'next/server';

export async function GET() {
  return NextResponse.json({
    status: 'ok',
    framework: 'nextjs',
    app: '${config.projectName || 'my-app'}',
    timestamp: new Date().toISOString(),
  });
}
`,
      },
      getStackmintLogoFile(),
      {
        path: 'src/components/.gitkeep',
        content: '',
      },
      {
        path: 'src/lib/.gitkeep',
        content: '',
      },
      {
        path: 'src/lib/stackmint-config.ts',
        content: `export interface StackMintConfig {
  projectName: string;
  framework: string;
  category: string;
  deployTarget: string;
  database: string;
  auth: string;
  apiLayer: string;
  validation: string;
  styling: string;
  uiLibrary: string;
  forms: string;
  stateManagement: string;
  dataFetching: string;
  ai: string;
  jobs: string;
  cache: string;
  email: string;
  payments: string;
  testing: string;
  docker: boolean;
  githubActions: boolean;
  husky: boolean;
  changesets: boolean;
  turborepo: boolean;
  baas: string;
  orm: string;
  packageManager: string;
  runtime: string;
}

export function getStackMintConfig(): StackMintConfig {
  return ${JSON.stringify({
    projectName: config.projectName || 'my-app',
    framework: config.framework || 'nextjs',
    category: config.category || 'fullstack',
    deployTarget: config.deployTarget || 'none',
    database: config.database || 'none',
    auth: config.auth || 'none',
    apiLayer: config.apiLayer || 'none',
    validation: config.validation || 'none',
    styling: config.styling || 'none',
    uiLibrary: config.uiLibrary || 'none',
    forms: config.forms || 'none',
    stateManagement: config.stateManagement || 'none',
    dataFetching: config.dataFetching || 'none',
    ai: config.ai || 'none',
    jobs: config.jobs || 'none',
    cache: config.cache || 'none',
    email: config.email || 'none',
    payments: config.payments || 'none',
    testing: config.testing || 'none',
    docker: !!config.docker,
    githubActions: !!config.githubActions,
    husky: !!config.husky,
    changesets: !!config.changesets,
    turborepo: !!config.turborepo,
    baas: config.baas || 'none',
    orm: config.orm || 'none',
    packageManager: config.packageManager || 'npm',
    runtime: config.runtime || 'node',
  }, null, 4)};
}


export function getFrameworkLabel(frameworkId: string): string {
  const labels: Record<string, string> = {
    'nextjs': 'Next.js 15 (App Router)',
    'sveltekit': 'SvelteKit',
    'nuxt': 'Nuxt 3',
    'react-router-v7': 'React Router v7 (Remix)',
    'analog': 'Analog (Angular)',
    'tanstack-start': 'TanStack Start',
    'astro-ssr': 'Astro (SSR mode)',
    'astro-ssg': 'Astro (SSG mode)',
    'react-vite': 'React + Vite',
    'vue-vite': 'Vue + Vite',
    'solid-vite': 'Solid + Vite',
    'svelte-vite': 'Svelte + Vite',
    'qwik': 'Qwik',
    'angular': 'Angular',
    'hono': 'Hono',
    'elysia': 'Elysia',
    'fastify': 'Fastify',
    'nestjs': 'NestJS',
    'express': 'Express',
    'nitro': 'Nitro',
    'h3': 'H3',
    'bun-native': 'Bun Native',
    'expo': 'Expo SDK 53',
    'react-native': 'React Native CLI',
    'vitepress': 'VitePress',
    'docusaurus': 'Docusaurus',
    'eleventy': 'Eleventy',
    'gatsby': 'Gatsby',
  };
  return labels[frameworkId] || frameworkId;
}

export function getSignals(config: StackMintConfig) {
  const signals = [];
  
  // Runtime signal
  signals.push({
    label: 'Runtime',
    value: getFrameworkLabel(config.framework),
    detail: getConfigDetail(config.framework, 'runtime')
  });
  
  // Styling signal
  if (config.styling && config.styling !== 'none') {
    signals.push({
      label: 'Styling',
      value: getStylingLabel(config.styling),
      detail: getConfigDetail(config.styling, 'styling')
    });
  }
  
  // Database signal
  if (config.database && config.database !== 'none') {
    signals.push({
      label: 'Database',
      value: getDatabaseLabel(config.database),
      detail: getConfigDetail(config.database, 'database')
    });
  }
  
  // Auth signal
  if (config.auth && config.auth !== 'none') {
    signals.push({
      label: 'Authentication',
      value: getAuthLabel(config.auth),
      detail: getConfigDetail(config.auth, 'auth')
    });
  }
  
  // API Layer signal
  if (config.apiLayer && config.apiLayer !== 'none') {
    signals.push({
      label: 'API Layer',
      value: getApiLayerLabel(config.apiLayer),
      detail: getConfigDetail(config.apiLayer, 'api')
    });
  }
  
  // Deploy signal
  signals.push({
    label: 'Deploy',
    value: getDeployLabel(config.deployTarget),
    detail: getConfigDetail(config.deployTarget, 'deploy')
  });
  
  return signals;
}

function getStylingLabel(styling: string): string {
  const labels: Record<string, string> = {
    'tailwind': 'Tailwind v4',
    'panda-css': 'Panda CSS',
    'stylex': 'StyleX',
    'css-modules': 'CSS Modules',
    'styled-components': 'Styled Components',
  };
  return labels[styling] || styling;
}

function getDatabaseLabel(database: string): string {
  const labels: Record<string, string> = {
    'postgres': 'PostgreSQL',
    'mysql': 'MySQL',
    'sqlite': 'SQLite',
    'mongodb': 'MongoDB',
    'turso': 'Turso',
    'neon': 'Neon',
  };
  return labels[database] || database;
}

function getAuthLabel(auth: string): string {
  const labels: Record<string, string> = {
    'better-auth': 'Better Auth',
    'clerk': 'Clerk',
    'next-auth': 'NextAuth.js',
    'lucia': 'Lucia Auth',
  };
  return labels[auth] || auth;
}

function getApiLayerLabel(apiLayer: string): string {
  const labels: Record<string, string> = {
    'trpc': 'tRPC',
    'orpc': 'ORPC',
    'ts-rest': 'ts-rest',
    'graphql': 'GraphQL',
    'rest': 'REST API',
  };
  return labels[apiLayer] || apiLayer;
}

function getDeployLabel(deployTarget: string): string {
  const labels: Record<string, string> = {
    'vercel': 'Vercel',
    'cloudflare-workers': 'Cloudflare Workers',
    'flyio': 'Fly.io',
    'railway': 'Railway',
    'self-hosted': 'Self-hosted',
  };
  return labels[deployTarget] || deployTarget;
}

function getConfigDetail(option: string, category: string): string {
  const details: Record<string, Record<string, string>> = {
    runtime: {
      'nextjs': 'App Router ready',
      'sveltekit': 'Full-stack Svelte',
      'nuxt': 'Vue 3 with SSR',
      'react-router-v7': 'Remix-style routing',
      'hono': 'Fast web framework',
    },
    styling: {
      'tailwind': 'Modern import pipeline',
      'panda-css': 'Atomic CSS with type safety',
      'stylex': 'Facebook\\'s CSS-in-JS',
      'css-modules': 'Scoped CSS modules',
    },
    database: {
      'postgres': 'Robust relational database',
      'mysql': 'Popular relational database',
      'sqlite': 'Lightweight file-based DB',
      'mongodb': 'NoSQL document store',
    },
    auth: {
      'better-auth': 'Modern auth solution',
      'clerk': 'Complete auth platform',
      'next-auth': 'OAuth and session management',
      'lucia': 'Flexible auth library',
    },
    api: {
      'trpc': 'End-to-end type safety',
      'orpc': 'OpenAPI-first RPC',
      'ts-rest': 'Type-safe REST clients',
      'graphql': 'Query language and runtime',
    },
    deploy: {
      'vercel': 'Serverless deployment',
      'cloudflare-workers': 'Edge computing platform',
      'flyio': 'App deployment platform',
      'railway': 'Cloud infrastructure',
    },
  };
  
  return details[category]?.[option] || 'Integrated feature';
}

export function getFrameworkDescription(config: StackMintConfig): string {
  const features = [];
  
  if (config.category === 'fullstack') {
    features.push('full-stack capabilities');
  }
  
  if (config.database && config.database !== 'none') {
    features.push('database integration');
  }
  
  if (config.auth && config.auth !== 'none') {
    features.push('authentication system');
  }
  
  if (config.apiLayer && config.apiLayer !== 'none') {
    features.push('type-safe API layer');
  }
  
  if (features.length === 0) {
    return 'Clean Next.js setup with modern tooling.';
  }
  
  return \`Next.js with \${features.join(', ')}.\`;
}
`,
      },
      {
        path: 'public/.gitkeep',
        content: '',
      },
      {
        path: 'next.config.ts',
        content: `import type { NextConfig } from 'next';

const nextConfig: NextConfig = {
  // Silences the workspace-root warning when multiple lockfiles are detected
  outputFileTracingRoot: process.cwd(),
  ${config.deployTarget === 'cloudflare-workers' ? "output: 'export'," : ''}
};

export default nextConfig;
`,
      },
      {
        path: 'tsconfig.json',
        content: JSON.stringify({
          compilerOptions: {
            target: 'ES2017',
            lib: ['dom', 'dom.iterable', 'esnext'],
            allowJs: true,
            skipLibCheck: true,
            strict: true,
            noEmit: true,
            esModuleInterop: true,
            module: 'esnext',
            moduleResolution: 'bundler',
            resolveJsonModule: true,
            isolatedModules: true,
            jsx: 'preserve',
            incremental: true,
            plugins: [{ name: 'next' }],
            paths: { '@/*': ['./src/*'] },
          },
          include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
          exclude: ['node_modules'],
        }, null, 2),
      },
    ];

    if (config.styling === 'tailwind' || config.styling === 'none') {
      files.push({
        path: 'postcss.config.mjs',
        content: `export default {
  plugins: {
    '@tailwindcss/postcss': {},
  },
};
`,
      });
    }

    return files;
  },
  scripts: {
    dev: 'next dev',
    build: 'next build',
    start: 'next start',
    lint: 'echo "No lint configured"',
  },
});