import { AdapterFile } from './index.js';

interface ProvidersConfig {
  framework?: string;
  auth?: string;
  apiLayer?: string;
  stateManagement?: string;
}

export function generateProviderComponents(config: ProvidersConfig): AdapterFile[] {
  const files: AdapterFile[] = [];
  const framework = config.framework || '';
  const isNextJs = framework.startsWith('next');
  const hasTrpc = config.apiLayer === 'trpc';
  const hasAuth = config.auth && config.auth !== 'none';

  // Root providers wrapper - wraps all client providers
  if (isNextJs) {
    files.push({
      path: 'src/components/providers/index.tsx',
      content: `'use client';

import { ReactNode } from 'react';
import { TRPCProvider } from './trpc-provider';
${hasAuth ? "import { AuthProvider } from './auth-provider';" : ''}

interface ProvidersProps {
  children: ReactNode;
}

/**
 * Root provider wrapper - all client providers should be added here
 * Order matters: innermost providers first
 */
export function Providers({ children }: ProvidersProps) {
  return (
    <TRPCProvider>
      ${hasAuth ? '<AuthProvider>' : ''}
        {children}
      ${hasAuth ? '</AuthProvider>' : ''}
    </TRPCProvider>
  );
}
`,
    });

    // Updated layout.tsx that uses providers
    files.push({
      path: 'src/app/layout.tsx',
      content: `import type { Metadata, Viewport } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Providers } from '@/components/providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'App | Built with stackmint',
  description: 'A full-stack app generated by stackmint.',
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
`,
    });

    // Enhanced tRPC provider with better defaults
    files.push({
      path: 'src/components/providers/trpc-provider.tsx',
      content: `'use client';

import { ReactNode, useState } from 'react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { httpBatchLink } from '@trpc/client';
import { trpc, getBaseUrl } from '@/utils/trpc';

interface TRPCProviderProps {
  children: ReactNode;
}

/**
 * tRPC + React Query provider
 * - Handles all server mutations and queries
 * - Batches requests automatically
 * - Includes automatic caching and stale data management
 */
export function TRPCProvider({ children }: TRPCProviderProps) {
  const [queryClient] = useState(
    () =>
      new QueryClient({
        defaultOptions: {
          queries: {
            staleTime: 60 * 1000, // 1 minute
            retry: 1,
          },
          mutations: {
            retry: 0,
          },
        },
      })
  );

  const [trpcClient] = useState(() =>
    trpc.createClient({
      links: [
        httpBatchLink({
          url: \`\${getBaseUrl()}/api/trpc\`,
          // Send cookies with requests (for auth)
          fetch: (url, options) =>
            fetch(url, {
              ...options,
              credentials: 'include',
            }),
        }),
      ],
    })
  );

  return (
    <trpc.Provider client={trpcClient} queryClient={queryClient}>
      <QueryClientProvider client={queryClient}>{children}</QueryClientProvider>
    </trpc.Provider>
  );
}
`,
    });

    // Auth provider (if auth is configured)
    if (hasAuth) {
      files.push({
        path: 'src/components/providers/auth-provider.tsx',
        content: `'use client';

import { ReactNode } from 'react';

interface AuthProviderProps {
  children: ReactNode;
}

/**
 * Authentication provider
 * - Wraps app with authentication context
 * - Session state is managed through useSession() hook
 */
export function AuthProvider({ children }: AuthProviderProps) {
  return <>{children}</>;
}
`,
      });

      // Auth hooks helper
      files.push({
        path: 'src/lib/hooks/useAuth.ts',
        content: `'use client';

import { useEffect, useState } from 'react';
import { authClient } from '@/lib/auth-client';

/**
 * Hook to get current auth session
 * Auto-updates when session changes
 */
export function useAuth() {
  const [session, setSession] = useState<unknown | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const getSession = async () => {
      try {
        // Get initial session
        const data = await authClient.getSession();
        setSession(data?.data?.session || null);
      } catch (error) {
        console.error('Failed to fetch session:', error);
        setSession(null);
      } finally {
        setLoading(false);
      }
    };

    getSession();
  }, []);

  return {
    session,
    loading,
    isAuthenticated: !!session,
  };
}
`,
      });
    }
  }

  // Common provider utilities
  files.push({
    path: 'src/lib/providers/context.ts',
    content: `import { createContext } from 'react';

/**
 * Theme context for light/dark mode
 */
export const ThemeContext = createContext<{
  theme: 'light' | 'dark';
  setTheme: (theme: 'light' | 'dark') => void;
}>({
  theme: 'light',
  setTheme: () => {},
});

/**
 * App context for global state
 */
export const AppContext = createContext<{
  isLoading: boolean;
  error: string | null;
}>({
  isLoading: false,
  error: null,
});
`,
  });

  return files;
}
