import { StackConfig } from '../../cli/types.js';

const FRAMEWORK_LABELS: Record<string, string> = {
  nextjs: 'Next.js 15',
  sveltekit: 'SvelteKit',
  nuxt: 'Nuxt 3',
  'react-router-v7': 'React Router v7',
  analog: 'Analog',
  'tanstack-start': 'TanStack Start',
  'astro-ssr': 'Astro SSR',
  'astro-ssg': 'Astro SSG',
  'react-vite': 'React Vite',
  'vue-vite': 'Vue Vite',
  'svelte-vite': 'Svelte Vite',
  'solid-vite': 'Solid Vite',
  qwik: 'Qwik',
  angular: 'Angular 19',
  nestjs: 'NestJS',
  express: 'Express',
  fastify: 'Fastify',
  hono: 'Hono',
  elysia: 'Elysia',
  bun: 'Bun',
  nitro: 'Nitro',
  h3: 'H3',
};

export function buildStackmintConfigLib(config: StackConfig): string {
  const frozen = {
    projectName: config.projectName || 'my-app',
    framework: config.framework || 'nextjs',
    category: config.category || 'fullstack',
    deployTarget: config.deployTarget || 'none',
    database: config.database || 'none',
    orm: config.orm || 'none',
    baas: config.baas || 'none',
    auth: config.auth || 'none',
    apiLayer: config.apiLayer || 'none',
    validation: config.validation || 'none',
    styling: config.styling || 'none',
    uiLibrary: config.uiLibrary || 'none',
    forms: config.forms || 'none',
    stateManagement: config.stateManagement || 'none',
    dataFetching: config.dataFetching || 'none',
    ai: config.ai || 'none',
    jobs: config.jobs || 'none',
    cache: config.cache || 'none',
    email: config.email || 'none',
    payments: config.payments || 'none',
    testing: config.testing || 'none',
    docker: !!config.docker,
    githubActions: !!config.githubActions,
    packageManager: config.packageManager || 'npm',
    runtime: config.runtime || 'node',
    monorepo: !!config.monorepo,
    aiConfig: config.aiConfig || [],
  };

  return `// Auto-generated by stackmint — do not edit manually.

export interface StackMintConfig {
  projectName: string; framework: string; category: string; deployTarget: string;
  database: string; orm: string; baas: string; auth: string; apiLayer: string;
  validation: string; styling: string; uiLibrary: string; forms: string;
  stateManagement: string; dataFetching: string; ai: string; jobs: string;
  cache: string; email: string; payments: string; testing: string;
  docker: boolean; githubActions: boolean; packageManager: string; runtime: string;
  monorepo: boolean; aiConfig: string[];
}

export function getStackMintConfig(): StackMintConfig {
  return ${JSON.stringify(frozen, null, 2)};
}

export function getFrameworkLabel(id: string): string {
  return ${JSON.stringify(FRAMEWORK_LABELS)}[id] ?? id;
}

export interface Signal { label: string; value: string; detail: string; }

export function getSignals(config: StackMintConfig): Signal[] {
  const s: Signal[] = [];
  s.push({ label: 'Framework', value: getFrameworkLabel(config.framework), detail: getFrameworkDetail(config.framework) });

  if (config.database !== 'none') {
    s.push({ label: 'Database', value: config.database, detail: 'Primary persistence' });
  } else if (config.baas !== 'none') {
    s.push({ label: 'Backend', value: config.baas, detail: 'Backend-as-a-Service' });
  }

  if (config.orm !== 'none') s.push({ label: 'ORM', value: config.orm, detail: 'Database access' });
  if (config.auth !== 'none') s.push({ label: 'Auth', value: config.auth, detail: 'Identity & Security' });
  if (config.apiLayer !== 'none') s.push({ label: 'API', value: config.apiLayer, detail: 'Data communication' });
  if (config.styling !== 'none') s.push({ label: 'Styling', value: config.styling, detail: 'Visual layer' });
  if (config.uiLibrary !== 'none') s.push({ label: 'UI', value: config.uiLibrary, detail: 'Component library' });
  if (config.ai !== 'none') s.push({ label: 'AI', value: config.ai, detail: 'Intelligence' });
  if (config.deployTarget !== 'none') s.push({ label: 'Deploy', value: config.deployTarget, detail: 'Cloud target' });

  return s;
}

function getFrameworkDetail(framework: string): string {
  const details: Record<string, string> = {
    nextjs: 'App Router · React 19',
    sveltekit: 'Svelte 5 · SSR',
    nuxt: 'Vue 3 · SSR',
    'react-router-v7': 'React 19 · SSR',
    analog: 'Angular 19 · SSR',
    'tanstack-start': 'React 19 · SSR',
    'astro-ssr': 'Astro · SSR',
    'astro-ssg': 'Astro · SSG',
    'react-vite': 'React 19 · SPA',
    'vue-vite': 'Vue 3 · SPA',
    'svelte-vite': 'Svelte 5 · SPA',
    'solid-vite': 'Solid · SPA',
    qwik: 'Qwik · Resumable',
    angular: 'Angular 19',
  };
  return details[framework] ?? 'TypeScript starter';
}

export function getFrameworkDescription(config: StackMintConfig): string {
  const parts: string[] = [];
  if (config.database !== 'none') parts.push('database');
  if (config.auth !== 'none') parts.push('auth');
  if (config.apiLayer !== 'none') parts.push('API');
  const fw = getFrameworkLabel(config.framework);
  return parts.length > 0 ? \`\${fw} with \${parts.join(', ')}.\` : \`\${fw} — Ready for production.\`;
}
`;
}

export const FRAMEWORK_DETAILS: Record<string, string> = {
  nextjs: 'App Router · React 19',
  sveltekit: 'Svelte 5 · SSR',
  nuxt: 'Vue 3 · SSR',
  'react-router-v7': 'React 19 · SSR',
  analog: 'Angular 19 · SSR',
  'tanstack-start': 'React 19 · SSR',
  'astro-ssr': 'Astro · SSR',
  'astro-ssg': 'Astro · SSG',
  'react-vite': 'React 19 · SPA',
  'vue-vite': 'Vue 3 · SPA',
  'svelte-vite': 'Svelte 5 · SPA',
  'solid-vite': 'Solid · SPA',
  qwik: 'Qwik · Resumable',
  angular: 'Angular 19',
};